version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18.x

    commands:
  pre_build:
    commands:
      -  npm i aws-sdk
      -  npm i -g serverless@3.2.1
      
  build:
    commands:
      - |- 
        serverless deploy
artifacts:
  files:
    - '**/*'
