service: api-testing

provider:
  name: aws
  runtime: nodejs20.x
  region: ap-south-1

functions:
  Lambdafunction:
    handler: handler.lambda_handler
    timeout: 30
    events:
      - http:
          path: /test
          method: GET
          cors: true
